--Les clients ayant participé le mois dernier plus que deux fois la moyenne générale de participations
--par client pendant cette période.On va prendre comme durée 1 an et pas 1 mois Dans notre cas  les
--sportifs qui ont participe cette année en moyenne deux fois aux meeting que les autres .
--Donc les participants dont la moyenne est 2 fois  > a celle des autres participants
