--La liste des clients ayant participé à au moins une réunion par mois dans les douze derniers mois.
--Impossible de prenndre au moins une réunion par mois car pas assez de compétitions par ans.
--On va donc prendre les compétitions sur une année et pour toute les disciplines et faire le compte
